services:
  web:
    build:
      context: .
      target: builder
      tags:
        - "cloud_watch_test:latest"
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    volumes:
      - ./app/log:/app/log

#    logging:
#      driver: awslogs
#      options:
#        awslogs-group: /my-app-log-group
#        awslogs-region: cn-north-1
##        awslogs-stream-prefix: cloud_watch_test
#        awslogs-create-group: "true"
#        awslogs-use-existing-group: "true"
#        awsaccesskeyid: ${AWS_ACCESS_KEY_ID}
#        awssecretkey: ${AWS_SECRET_ACCESS_KEY}